version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    container_name: mongodb
    ports:
      - 27017:27017
  app:
    depends_on:
      - mongodb
    build: .
    ports:
      - 4000:4000
    entrypoint: "node index.js"